import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/custom-ui/layout/navbar.component";
import { Toaster } from "react-hot-toast";
import Provider from "@/components/providers/SessionProvider";
import QueryProvider from "@/components/providers/QueryProvider";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <QueryProvider>
            <main className="h-screen flex flex-col justify-center items-center">
              <Navbar />
              {children}
            </main>
            <Toaster />
          </QueryProvider>
        </Provider>
      </body>
    </html>
  );
}
